### ISSUE TITLE
[Node.js Bootcamp] Project 0: Proxy Server - Ready for Review

### ISSUE THREAD

**Issue by ajayvasagiri** [ajayvasagiri/nodedotjs#2]
My app is complete. /cc @codepathreview @codepath

**Comment by CrabDude** [comment]
Please mark the "Required"s that have been completed.

You are missing a proper README. This submission is incomplete until you include a proper README.md which includes both "Time Spent" and checked list of "Required"s. 

Please see the [Submitting Assignments Guide](http://courses.codepath.com/snippets/nodejs_fast_track/submitting_assignments) for how to properly submit an assignment.
